import os
import datetime
import time
import httpx
import jwt
from dotenv import load_dotenv
from livekit import api
from livekit import rtc
import asyncio

load_dotenv("c:/AI-Career-Coach/AI-Career-Coach-Backend/.env")

LIVEKIT_URL = os.getenv("LIVEKIT_URL")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")
TAVUS_API_KEY = os.getenv("TAVUS_API_KEY")

# Let's inspect the exact JWT payload generated by livekit.api.AccessToken
grant = api.VideoGrants(
    room_join=True,
    room="test_room_nbf",
    can_publish=True,
    can_subscribe=True,
    can_publish_data=True,
)

tok_builder = (
    api.AccessToken(api_key=LIVEKIT_API_KEY, api_secret=LIVEKIT_API_SECRET)
    .with_identity("tavus_avatar_interviewer")
    .with_name("AI HR Interviewer – Professional")
    .with_grants(grant)
    .with_ttl(datetime.timedelta(hours=2))
)

official_jwt = tok_builder.to_jwt()
decoded = jwt.decode(official_jwt, LIVEKIT_API_SECRET, algorithms=["HS256"])
print("Official JWT Decoded Payload:")
import json
print(json.dumps(decoded, indent=2))

# Now let's create the EXACT same payload with nbf = now - 120
now = int(time.time())
decoded["nbf"] = now - 120
decoded["iat"] = now - 120

skew_immune_jwt = jwt.encode(decoded, LIVEKIT_API_SECRET, algorithm="HS256")

# 1. Test skew_immune_jwt with livekit TokenVerifier
verifier = api.TokenVerifier(api_key=LIVEKIT_API_KEY, api_secret=LIVEKIT_API_SECRET)
verified_claims = verifier.verify(skew_immune_jwt)
print("\nVerified by LiveKit TokenVerifier:", verified_claims.identity)

# 2. Test skew_immune_jwt with LiveKit Cloud Room connect
async def test_livekit_connect():
    room = rtc.Room()
    await room.connect(LIVEKIT_URL, skew_immune_jwt)
    print("LiveKit Cloud connection: SUCCESS! Room:", room.name)
    await room.disconnect()

asyncio.run(test_livekit_connect())

# 3. Test skew_immune_jwt with Tavus API
with httpx.Client(timeout=30.0) as client:
    resp = client.post(
        "https://tavusapi.com/v2/conversations",
        headers={
            "x-api-key": TAVUS_API_KEY,
            "Content-Type": "application/json",
        },
        json={
            "pal_id": "p5277ac17937",
            "face_id": "r3f427f43c9d",
            "properties": {
                "livekit_ws_url": LIVEKIT_URL,
                "livekit_room_token": skew_immune_jwt,
            }
        }
    )
    print(f"\nTavus API status: {resp.status_code}")
    print(f"Tavus API body: {resp.text}")
    if resp.status_code in (200, 201):
        cid = resp.json()["conversation_id"]
        client.delete(f"https://tavusapi.com/v2/conversations/{cid}", headers={"x-api-key": TAVUS_API_KEY})
        print("Tavus conversation cleaned up.")
